development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9f0abdcd95126adb9e4ac829f716463b@crestfish.redistogo.com:10790/
  channel_prefix: fb_app_production
